### ISSUE TITLE
Error 3003: Not a mix-integer problem

### ISSUE THREAD

**Issue by pmcvay** [JuliaOpt/CPLEX.jl#173] opened 2018-05-30 18:46 UTC
I get a error that my optimization formulation is not a mix-integer problem but it is solved anyways. Here is a simple example showing it.

```
m = Model(solver = CplexSolver())

@variable(m, 0 <= x <= 2 )
@objective(m, Min, (x-1)^2 + 10)
status = solve(m)

println("Objective value: ", getobjectivevalue(m))
println("x = ", getvalue(x))
```

And the output is:

```
julia> :Min

julia> Tried aggregator 1 time.
QP Presolve eliminated 0 rows and 1 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)
Barrier time = 0.00 sec. (0.00 ticks)

Total time on 8 threads = 0.00 sec. (0.00 ticks)
CPLEX Error  3003: Not a mixed-integer problem.
:Optimal

julia> 
julia> Objective value: 10.0

julia> x = 1.0

```

**Comment by joehuchette** [comment] 2018-05-30 18:54
I can reproduce this. As you observe, this doesn't really affect anything, but we should fix anyway. It's likely occurring when we query the solver for solution information after it terminates.

**Comment by joehuchette** [comment] 2018-05-30 19:05
Error seems to be occurring here: https://github.com/JuliaOpt/JuMP.jl/blob/3e261f8ba7318a83292a2374ce317864ac1ea1a8/src/solvers.jl#L251

**Comment by odow** [comment] 2019-11-04 21:33
Closing since we won't be fixing this in the MPB wrapper. The MOI wrapper now calls the objective bound for MIP problems, or the objective value for linear problems.

**Closed by odow** 2019-11-04 21:33 UTC
Labels: MBP API
