### ISSUE TITLE
is_apple not defined

### ISSUE THREAD

**Issue by ArielxX** [JuliaOpt/CPLEX.jl#253] opened 2019-09-19 15:56 UTC
Hi, I'm trying to install the CPLEX package for julia. I'm using linux (ubuntu) x64. My julia version is 1.2.0. I have already installed CPLEX.

I have this in my /.bashrc:

`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/bin/x86-64_linux"`

Also I wrote this in julia:

`ENV["CPLEX_STUDIO_BINARIES"]="/opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/bin/x86-64_linux"`

But, when I try to make the build, that's what happen:

```
julia> Pkg.build("CPLEX")
  Building CPLEX → '~/.julia/packages/CPLEX/FUtHu/deps/build.log'
┌ Error: Error building 'CPLEX': 
│ ERROR: LoadError: UndefVarError: is_apple not defined
│ Stacktrace:
│  [1] top-level scope at /home/arielxx/.julia/packages/CPLEX/FUtHu/deps/build.jl:18
│  [2] include at ./boot.jl:328 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1094
│  [4] include(::Module, ::String) at ./Base.jl:31
│  [5] include(::String) at ./client.jl:431
│  [6] top-level scope at none:5
│ in expression starting at /home/arielxx/.julia/packages/CPLEX/FUtHu/deps/build.jl:18
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/backwards_compatible_isolation.jl:647
false
```

Please, I will thank a lot any help you can provide.

**Comment by odow** [comment] 2019-09-19 17:11
CPLEX.jl has not been updated to Julia 1.2. Closing as a duplicate of #252.

**Closed by odow** 2019-09-19 17:11 UTC

**Comment by ArielxX** [comment] 2019-09-19 17:22
> CPLEX.jl has not been updated to Julia 1.2. Closing as a duplicate of #252.

ohhh, Ok. I thought that. Maybe I can go back to another version. Maybe the 1.0.4?

Thank you very much

**Comment by odow** [comment] 2019-09-19 18:37
I believe Julia 1.0.x or 1.1.x should work.
