### ISSUE TITLE
Supporting CPLEX version 12.10

### ISSUE THREAD

**Issue by mkhraijah** [JuliaOpt/CPLEX.jl#293] opened 2020-04-05 07:15 UTC
Hi, 

Thanks in advance for your efforts and support. I would like to file an issue regarding supporting CPLEX version 12.10. As I noticed the CPLEX version supported by JuMP are 12.8 and 12.9, and I want to ask if there is a way to install 12.10 version interface with the current settings. 

Thanks again, 
Mohannad

**Comment by odow** [comment] 2020-04-05 14:56
Closing as duplicate of #270.

**Closed by odow** 2020-04-05 14:56 UTC
